# --- !Ups
create table "albums" (
  "id" int generated always as identity null ,
  "artist" varchar not null,
  "name"   varchar not null,
  "genre"   varchar not null,
  PRIMARY KEY ( "artist", "name")
);
create table "songs" (
  "songId" int generated always as identity(start with 1) not null,
  "title" varchar not null,
  "duration" varchar not null,
  PRIMARY KEY ("title", "duration")
);
create table "album_song" (
  "albumID" int not null ,
  "songID" int not null,
  PRIMARY KEY ("albumID", "songID")
);
create table "playing" (
  "playingId" int generated by default as identity(start with 1) not null primary key,
  "artist" varchar not null,
  "song"   varchar not null,
  "user"   varchar not null
);
create table "playing_song" (
  "albumId" int not null ,
  "songId" int not null,
  "playingId" int not null
);
# --- !Downs

drop table "albums" if exists;
drop table "songs" if exists;
drop table "album_song" if exists;
drop table "playing" if exists;
drop table "playing_song" if exists;