version: "3.8"
services:
  web:
    build: .
    ports:
      - "9000:9000"
  db:
    image: postgres
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
    - "5433:5432"